//! Exact exporter for Ironwood's Orchard Action circuit fixtures.

use halo2_proofs::{
    dev::circuit_fixture::{CircuitFixtureRecorder, LeanEnvironment},
    plonk::{Circuit as Halo2Circuit, ConstraintSystem, FloorPlanner},
};
use pasta_curves::pallas;

const K: u32 = 11;
const ACTION_SELMAP_HEADER: &str =
    "-- Auto-generated by `layout_dump::dump_layout_action` (orchard checkout).
-- Selector-compression map for the full Orchard Action circuit. Do not edit by hand.";
const LEAN_ENVIRONMENT: LeanEnvironment<'static> = LeanEnvironment {
    fixture_import: "Zcash.Circuits.Fixtures.FixtureTypes",
    fixture_namespace: "Zcash.Circuits.Fixtures",
    open_namespace: "Fixtures",
};

fn capture_action_version(
    version: crate::circuit::OrchardCircuitVersion,
) -> (
    ConstraintSystem<pallas::Base>,
    CircuitFixtureRecorder<pallas::Base>,
) {
    let circuit = crate::circuit::Circuit::empty(version);
    let mut meta = ConstraintSystem::<pallas::Base>::default();
    let config = <crate::circuit::Circuit as Halo2Circuit<pallas::Base>>::configure(&mut meta);
    let constants = meta.lean_dump_constants();
    let mut recorder = CircuitFixtureRecorder::default();
    <crate::circuit::Circuit as Halo2Circuit<pallas::Base>>::FloorPlanner::synthesize(
        &mut recorder,
        &circuit,
        config,
        constants,
    )
    .expect("synthesis should succeed");
    (meta, recorder)
}

/// Writes the four Orchard-owned Action fixtures in Ironwood's exact JSON and Lean formats.
///
/// Run with:
/// `IRONWOOD_ACTION_FIXTURE_OUT=/path/to/Zcash/Circuits/Fixtures cargo test --release \
///   -p orchard --lib circuit::layout_dump::dump_ironwood_action_fixtures \
///   --features circuit-fixtures -- --ignored --nocapture`
#[test]
#[ignore = "writes generated Ironwood Action fixture files"]
fn dump_ironwood_action_fixtures() {
    use std::fs;
    use std::path::PathBuf;
    use std::println;

    let output_dir = PathBuf::from(
        std::env::var_os("IRONWOOD_ACTION_FIXTURE_OUT")
            .expect("set IRONWOOD_ACTION_FIXTURE_OUT to the destination fixture directory"),
    );
    fs::create_dir_all(&output_dir).expect("create fixture output directory");

    let n = 1 << K;
    let (action_meta, action_recorder) =
        capture_action_version(crate::circuit::OrchardCircuitVersion::PostNu6_3);
    let (base_meta, base_recorder) =
        capture_action_version(crate::circuit::OrchardCircuitVersion::FixedPostNu6_2);
    let fixtures = [
        (
            "ActionSelMap.lean",
            action_recorder.render_selector_map_lean(
                &action_meta,
                n,
                ACTION_SELMAP_HEADER,
                LEAN_ENVIRONMENT,
                "actionSelMap",
                false,
            ),
        ),
        (
            "actionPost.json",
            action_recorder.render_cs_json(&action_meta, n),
        ),
        (
            "actionLayout.json",
            // Preserve the original capture's generator-table fill block order.
            action_recorder.render_layout_json(&action_meta, K, &[1, 2, 0]),
        ),
        (
            "actionBaseLayout.json",
            base_recorder.render_layout_json(&base_meta, K, &[2, 1, 0]),
        ),
    ];

    for (name, contents) in fixtures {
        let path = output_dir.join(name);
        fs::write(&path, contents).unwrap_or_else(|error| {
            panic!("write {}: {}", path.display(), error);
        });
        println!("wrote {}", path.display());
    }
}
